version: "3.7"
services:
  da-postgres:
    container_name: da-postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./posgres.${APP_ENV}.env
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    networks:
      - da-network
  da-decision-service:
    container_name: da-decision-service
    build:
      context: ./da-decision-service/
      dockerfile: ./da-decision-service.${APP_ENV}.dockerfile
    ports:
      - "7032:7032"
    networks:
      - da-network
    depends_on:
      - da-postgres
  da-user-service:
    container_name: da-user-service
    build:
      context: ./da-user-service/
      dockerfile: ./da-user-service.${APP_ENV}.dockerfile
    ports:
      - "7087:7087"
    networks:
      - da-network
    depends_on:
      - da-postgres
  da-gateway-service:
    container_name: da-gateway-service
    build:
      context: ./da-gateway-service/
      dockerfile: ./da-gateway-service.${APP_ENV}.dockerfile
    ports:
      - "7049:7049"
    networks:
      - da-network
networks:
  da-network:
    driver: bridge