export default {
  // users
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  // decisions
  LOAD_DECISIONS: "LOAD_DECISIONS",
  GET_DECISION: "GET_DECISION",
  ADD_DECISION: "ADD_DECISION",
  UPDATE_DECISION: "UPDATE_DECISION",
  DELETE_DECISION: "DELETE_DECISION",
};
