export default {
  // decisions
  LOAD_DECISIONS: "LOAD_DECISIONS",
  GET_DECISION: "GET_DECISION",
  ADD_DECISION: "ADD_DECISION",
  UPDATE_DECISION: "UPDATE_DECISION",
  DELETE_DECISION: "DELETE_DECISION",
};
