export default {
  // decisions
  LOAD_DECISIONS: "LOAD_DECISIONS",
  ADD_DECISION: "ADD_DECISION",
  UPDATE_DECISION: "UPDATE_DECISION",
  DELETE_DECISION: "DELETE_DECISION",
  // criteria
  DELETE_CRITERIA: "DELETE_CRITERIA",
  // alternative
  DELETE_ALTERNATIVE: "DELETE_ALTERNATIVE",
};
